// <auto-generated />
using System;
using CyberBoardAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyberBoardAPI.Migrations
{
    [DbContext(typeof(CyberBoardDBContext))]
    [Migration("20251114102516_email_added")]
    partial class email_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgentMission", b =>
                {
                    b.Property<Guid>("AgentsAssignedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MissionsAssignedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AgentsAssignedId", "MissionsAssignedId");

                    b.HasIndex("MissionsAssignedId");

                    b.ToTable("AgentMission");
                });

            modelBuilder.Entity("CyberBoardAPI.Entities.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("CyberBoardAPI.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("CyberBoardAPI.Entities.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("CyberBoardAPI.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetAgentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TargetAgentId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AgentMission", b =>
                {
                    b.HasOne("CyberBoardAPI.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsAssignedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyberBoardAPI.Entities.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionsAssignedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberBoardAPI.Entities.Agent", b =>
                {
                    b.HasOne("CyberBoardAPI.Entities.Agency", "Agency")
                        .WithMany("Agents")
                        .HasForeignKey("AgencyId");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("CyberBoardAPI.Entities.Notification", b =>
                {
                    b.HasOne("CyberBoardAPI.Entities.Agent", "TargetAgent")
                        .WithMany("Notifications")
                        .HasForeignKey("TargetAgentId");

                    b.Navigation("TargetAgent");
                });

            modelBuilder.Entity("CyberBoardAPI.Entities.Agency", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("CyberBoardAPI.Entities.Agent", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
